name: Deploy Firebase

on:
  push:
    branches:
      - deploy-setting

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Authenticate to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT}" > "${HOME}/firebase-service-account.json"
          firebase auth:login:ci --token "$(firebase login:ci --no-localhost --interactive < "${HOME}/firebase-service-account.json")"
      - name: Deploy to Firebase (Staging)
        if: github.ref == 'refs/heads/deploy-setting'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          firebase use --add ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} -y
          npx firebase deploy --only hosting:staging
      - name: Deploy to Firebase (Production)
        if: github.ref == 'refs/heads/main'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          firebase use --add ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} -y
          npx firebase deploy --only hosting:production