name: Deploy Firebase

on:
  push:
    branches:
      - deploy-setting

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Authenticate to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/firebase-service-account.json"
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${HOME}/firebase-service-account.json"
      - name: Deploy to Firebase (Staging)
        if: github.ref == 'refs/heads/deploy-setting'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/firebase-service-account.json"
        run: |
          npx firebase deploy --only hosting:staging --project=${{ secrets.PROJECT_ID }}
      - name: Deploy to Firebase (Production)
        if: github.ref == 'refs/heads/main'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/firebase-service-account.json"
        run: |
          npx firebase deploy --only hosting:production --project=${{ secrets.PROJECT_ID }}